server:
  port: 8888
  mode: release

database:
  driver: mysql
  host: 1Panel-mysql-1DJG
  port: 3306
  username: gin-react_admin
  password: "Tr4i7yNccYnXC2HC"
  dbname: gin-react_admin
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

jwt:
  secret: "SIZtvT0ckI9WCj488ZuiCYd/VH4WOiDDyK08qjrfE7s="
  expire: 7200
  refresh_expire: 604800  # refresh token 过期时间（秒）7天
redis:
  addr: "1Panel-redis-Yqvz:6379"
  password: "redis_8Q68AT"
  db: 9
  pool_size: 10
log:
  level: info
  format: json

snowflake:
  machine_id: 1
